name: aamar_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  device_preview: ^1.1.0
  dio: ^5.3.0
  skeletons: ^0.0.3
  shared_preferences: ^2.2.0
  sqflite_common_ffi: ^2.2.5
  sqflite: ^2.2.8+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

